{
 "title": "IV_Curve Plot for MMTS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "stage1: Ambient-Roomtemp",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH\n\tLATEST_STAGES AS (\n\t\tSELECT DISTINCT\n\t\t\tON (SPLIT_PART(COMMENT, '-', 1)) SPLIT_PART(COMMENT, '-', 1) AS STAGE,\n\t\t\tCOMMENT,\n\t\t\tTO_DATE(SPLIT_PART(COMMENT, '-', 2), 'YYYYMMDD') AS TEST_DATE\n\t\tFROM\n\t\t\tPUBLIC.MODULE_IV_TEST\n\t\tWHERE\n\t\t\tCOMMENT ~ '^stage[1-4]-[0-9]{8}$'\n\t\tORDER BY\n\t\t\tSPLIT_PART(COMMENT, '-', 1),\n\t\t\tTO_DATE(SPLIT_PART(COMMENT, '-', 2), 'YYYYMMDD') DESC\n\t),\n\tSELECTED_STAGE AS (\n\t\tSELECT\n\t\t\tCOMMENT\n\t\tFROM\n\t\t\tLATEST_STAGES\n\t\tWHERE\n\t\t\tSTAGE = 'stage1'\n\t),\n\tFILTERED_IV AS (\n\t\tSELECT\n\t\t\tM.*,\n\t\t\tM.MEAS_I[ARRAY_LENGTH(M.MEAS_I, 1)] AS I_LAST\n\t\tFROM\n\t\t\tMODULE_IV_TEST AS M\n\t\t\tJOIN SELECTED_STAGE AS L ON M.COMMENT = L.COMMENT\n\t),\n\tUNNESTED AS (\n\t\tSELECT\n\t\t\tMODULE_NAME,\n\t\t\tABS(V) AS ABSV,\n\t\t\tI,\n\t\t\t(DATE_TEST + TIME_TEST) AS TESTTIMESTAMP\n\t\tFROM\n\t\t\tFILTERED_IV,\n\t\t\tUNNEST(PROGRAM_V, MEAS_I) AS T (V, I) -- use program_v instead of meas_v since the case 0 volt from keithley hits compliance.\n\t)\nSELECT\n\tMODULE_NAME,\n\tABSV,\n\tI\nFROM\n\tUNNESTED\nWHERE\n\tABSV != 0 -- voltage=0 means module hits compliance current\nORDER BY\n\tTESTTIMESTAMP,\n\tRIGHT(MODULE_NAME, 4) ASC,\n\tABSV ASC;"
    }
   ]
  },
  {
   "title": "stage2: first Dry-Lowtemp",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "WITH\n\tLATEST_STAGES AS (\n\t\tSELECT DISTINCT\n\t\t\tON (SPLIT_PART(COMMENT, '-', 1)) SPLIT_PART(COMMENT, '-', 1) AS STAGE,\n\t\t\tCOMMENT,\n\t\t\tTO_DATE(SPLIT_PART(COMMENT, '-', 2), 'YYYYMMDD') AS TEST_DATE\n\t\tFROM\n\t\t\tPUBLIC.MODULE_IV_TEST\n\t\tWHERE\n\t\t\tCOMMENT ~ '^stage[1-4]-[0-9]{8}$'\n\t\tORDER BY\n\t\t\tSPLIT_PART(COMMENT, '-', 1),\n\t\t\tTO_DATE(SPLIT_PART(COMMENT, '-', 2), 'YYYYMMDD') DESC\n\t),\n\tSELECTED_STAGE AS (\n\t\tSELECT\n\t\t\tCOMMENT\n\t\tFROM\n\t\t\tLATEST_STAGES\n\t\tWHERE\n\t\t\tSTAGE = 'stage2'\n\t),\n\tFILTERED_IV AS (\n\t\tSELECT\n\t\t\tM.*,\n\t\t\tM.MEAS_I[ARRAY_LENGTH(M.MEAS_I, 1)] AS I_LAST\n\t\tFROM\n\t\t\tMODULE_IV_TEST AS M\n\t\t\tJOIN SELECTED_STAGE AS L ON M.COMMENT = L.COMMENT\n\t),\n\tUNNESTED AS (\n\t\tSELECT\n\t\t\tMODULE_NAME,\n\t\t\tABS(V) AS ABSV,\n\t\t\tI,\n\t\t\t(DATE_TEST + TIME_TEST) AS TESTTIMESTAMP\n\t\tFROM\n\t\t\tFILTERED_IV,\n\t\t\tUNNEST(PROGRAM_V, MEAS_I) AS T (V, I) -- use program_v instead of meas_v since the case 0 volt from keithley hits compliance.\n\t)\nSELECT\n\tMODULE_NAME,\n\tABSV,\n\tI\nFROM\n\tUNNESTED\nWHERE\n\tABSV != 0 -- voltage=0 means module hits compliance current\nORDER BY\n\tTESTTIMESTAMP,\n\tRIGHT(MODULE_NAME, 4) ASC,\n\tABSV ASC;"
    }
   ]
  },
  {
   "title": "stage3: Dry-low temperature AFTER thermal cycle",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "WITH\n\tLATEST_STAGES AS (\n\t\tSELECT DISTINCT\n\t\t\tON (SPLIT_PART(COMMENT, '-', 1)) SPLIT_PART(COMMENT, '-', 1) AS STAGE,\n\t\t\tCOMMENT,\n\t\t\tTO_DATE(SPLIT_PART(COMMENT, '-', 2), 'YYYYMMDD') AS TEST_DATE\n\t\tFROM\n\t\t\tPUBLIC.MODULE_IV_TEST\n\t\tWHERE\n\t\t\tCOMMENT ~ '^stage[1-4]-[0-9]{8}$'\n\t\tORDER BY\n\t\t\tSPLIT_PART(COMMENT, '-', 1),\n\t\t\tTO_DATE(SPLIT_PART(COMMENT, '-', 2), 'YYYYMMDD') DESC\n\t),\n\tSELECTED_STAGE AS (\n\t\tSELECT\n\t\t\tCOMMENT\n\t\tFROM\n\t\t\tLATEST_STAGES\n\t\tWHERE\n\t\t\tSTAGE = 'stage3'\n\t),\n\tFILTERED_IV AS (\n\t\tSELECT\n\t\t\tM.*,\n\t\t\tM.MEAS_I[ARRAY_LENGTH(M.MEAS_I, 1)] AS I_LAST\n\t\tFROM\n\t\t\tMODULE_IV_TEST AS M\n\t\t\tJOIN SELECTED_STAGE AS L ON M.COMMENT = L.COMMENT\n\t),\n\tUNNESTED AS (\n\t\tSELECT\n\t\t\tMODULE_NAME,\n\t\t\tABS(V) AS ABSV,\n\t\t\tI,\n\t\t\t(DATE_TEST + TIME_TEST) AS TESTTIMESTAMP\n\t\tFROM\n\t\t\tFILTERED_IV,\n\t\t\tUNNEST(PROGRAM_V, MEAS_I) AS T (V, I) -- use program_v instead of meas_v since the case 0 volt from keithley hits compliance.\n\t)\nSELECT\n\tMODULE_NAME,\n\tABSV,\n\tI\nFROM\n\tUNNESTED\nWHERE\n\tABSV != 0 -- voltage=0 means module hits compliance current\nORDER BY\n\tTESTTIMESTAMP,\n\tRIGHT(MODULE_NAME, 4) ASC,\n\tABSV ASC;"
    }
   ]
  },
  {
   "title": "stage4: Dry-Room temperature AFTER thermal cycle",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "WITH\n\tLATEST_STAGES AS (\n\t\tSELECT DISTINCT\n\t\t\tON (SPLIT_PART(COMMENT, '-', 1)) SPLIT_PART(COMMENT, '-', 1) AS STAGE,\n\t\t\tCOMMENT,\n\t\t\tTO_DATE(SPLIT_PART(COMMENT, '-', 2), 'YYYYMMDD') AS TEST_DATE\n\t\tFROM\n\t\t\tPUBLIC.MODULE_IV_TEST\n\t\tWHERE\n\t\t\tCOMMENT ~ '^stage[1-4]-[0-9]{8}$'\n\t\tORDER BY\n\t\t\tSPLIT_PART(COMMENT, '-', 1),\n\t\t\tTO_DATE(SPLIT_PART(COMMENT, '-', 2), 'YYYYMMDD') DESC\n\t),\n\tSELECTED_STAGE AS (\n\t\tSELECT\n\t\t\tCOMMENT\n\t\tFROM\n\t\t\tLATEST_STAGES\n\t\tWHERE\n\t\t\tSTAGE = 'stage4'\n\t),\n\tFILTERED_IV AS (\n\t\tSELECT\n\t\t\tM.*,\n\t\t\tM.MEAS_I[ARRAY_LENGTH(M.MEAS_I, 1)] AS I_LAST\n\t\tFROM\n\t\t\tMODULE_IV_TEST AS M\n\t\t\tJOIN SELECTED_STAGE AS L ON M.COMMENT = L.COMMENT\n\t),\n\tUNNESTED AS (\n\t\tSELECT\n\t\t\tMODULE_NAME,\n\t\t\tABS(V) AS ABSV,\n\t\t\tI,\n\t\t\t(DATE_TEST + TIME_TEST) AS TESTTIMESTAMP\n\t\tFROM\n\t\t\tFILTERED_IV,\n\t\t\tUNNEST(PROGRAM_V, MEAS_I) AS T (V, I) -- use program_v instead of meas_v since the case 0 volt from keithley hits compliance.\n\t)\nSELECT\n\tMODULE_NAME,\n\tABSV,\n\tI\nFROM\n\tUNNESTED\nWHERE\n\tABSV != 0 -- voltage=0 means module hits compliance current\nORDER BY\n\tTESTTIMESTAMP,\n\tRIGHT(MODULE_NAME, 4) ASC,\n\tABSV ASC;"
    }
   ]
  }
 ]
}