{
 "title": "Thermal Box Environment History",
 "description": "Use module ID searching for historical environments",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "selected_module_name",
    "label": "module ID",
    "query": "SELECT module_name\nFROM (\n    SELECT DISTINCT \n        module_name,\n        RIGHT(module_name, 4) AS suffix\n    FROM module_iv_test\n\tWHERE module_name LIKE '320%'\n) t\nORDER BY suffix DESC LIMIT 15;"
   },
   {
    "name": "test_timestamp",
    "query": "        WITH latest_qc_summary AS (\n            SELECT DISTINCT ON (module_name) *\n            FROM module_qc_summary\n            ORDER BY module_name, mod_qc_no DESC\n        ), \n\n        latest_iv_test AS (\n            SELECT DISTINCT ON (mod_ivtest_no) *\n            FROM module_iv_test\n            WHERE meas_v IS NOT NULL AND meas_i IS NOT NULL\n            AND array_length(meas_v, 1) = array_length(meas_i, 1)\n            AND module_name = '${selected_module_name}'\n            ORDER BY mod_ivtest_no DESC\n        )\n\n        SELECT (date_test + time_test)::TEXT AS test_timestamp\n        FROM latest_iv_test\n        ORDER BY mod_ivtest_no DESC;\n        \n"
   }
  ]
 },
 "panels": [
  {
   "title": "List of IV curve data for Module",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "hgcdb",
     "rawSql": "        WITH latest_iv_test AS (\n            SELECT DISTINCT ON (mod_ivtest_no) *\n            FROM module_iv_test\n            WHERE meas_v IS NOT NULL AND meas_i IS NOT NULL\n            AND array_length(meas_v, 1) = array_length(meas_i, 1)\n            AND module_name = '${selected_module_name}'\n            AND status = 8\n            ORDER BY mod_ivtest_no DESC\n        )\n\n        SELECT module_name, (date_test + time_test) AS test_timestamp,  rel_hum, temp_c, inspector\n        FROM latest_iv_test\n        ORDER BY mod_ivtest_no DESC;\n        \n"
    }
   ]
  },
  {
   "title": "Temperatures (+-6Hours)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "\nSELECT * FROM (\n  SELECT '${test_timestamp}'::timestamptz AS \"time\", -45 AS test_timestamp\n  UNION ALL\n  SELECT '${test_timestamp}'::timestamptz+ INTERVAL '1second' AS \"time\", 25 AS test_timestamp\n) t"
    },
    {
     "dataset": "hgcdb",
     "rawSql": "\n  SELECT \n    measured_at AS \"time\" ,\n    'temperature' AS sensor_id ,    value AS target\n    FROM measurement WHERE\n         measured_at BETWEEN \n        TIMESTAMP '${test_timestamp}' - INTERVAL '6 hours'\n        AND\n        TIMESTAMP '${test_timestamp}' + INTERVAL '6 hours'\n        AND sensor_id LIKE 'Chiller-T' \n    ORDER BY measured_at \n    ASC \n    LIMIT 10000;\n"
    },
    {
     "dataset": "hgcdb",
     "rawSql": "\n  SELECT \n    measured_at AS \"time\" ,\n    sensor_id ,    value AS sensor\n    FROM measurement WHERE\n         measured_at BETWEEN \n        TIMESTAMP '${test_timestamp}' - INTERVAL '6 hours'\n        AND\n        TIMESTAMP '${test_timestamp}' + INTERVAL '6 hours'\n        AND sensor_id LIKE 'RTD-%' \n    ORDER BY measured_at \n    ASC \n    LIMIT 10000;\n"
    }
   ]
  },
  {
   "title": "Dew Point (+-6Hours)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "PLC_COLLECT",
     "rawSql": "\nSELECT * FROM (\n  SELECT '${test_timestamp}'::timestamptz AS \"time\", -55 AS test_timestamp\n  UNION ALL\n  SELECT '${test_timestamp}'::timestamptz+ INTERVAL '1second' AS \"time\", 20 AS test_timestamp\n) t"
    },
    {
     "dataset": "hgcdb",
     "rawSql": "\n  SELECT \n    measured_at AS \"time\" ,\n    sensor_id ,    value AS sensor\n    FROM measurement WHERE\n         measured_at BETWEEN \n        TIMESTAMP '${test_timestamp}' - INTERVAL '6 hours'\n        AND\n        TIMESTAMP '${test_timestamp}' + INTERVAL '6 hours'\n        AND (sensor_id LIKE 'DMT-%' )\n    ORDER BY measured_at \n    ASC \n    LIMIT 10000"
    }
   ]
  }
 ]
}